### ISSUE TITLE
More TODO

### ISSUE THREAD

**Issue by ryanlevy** [JoeyT1994/ITensorNumericalAnalysis.jl#12]
- [x] don't hardcode binary
- [ ] "expect" (take list of projections and get values; contract more than one point at a time)
   - [ ] get all bitstrings of a bitmap and their values
- [x] Maybe swap project for slices instead of multiply calls
- [ ] building grid tools
- [ ] Docstrings for functions
- [ ] Add formatting as commit hook
- [ ]  From discussion: swap left,right boundary to tuple and include default of size 1 to exand
